name = "cloudflare-demo-hub-credential-stuffing"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "cloudflare-demo-hub-credential-stuffing"

[env.production.vars]
AUTH_VALID_USERNAME = "jcarvalho@myemail.com"
AUTH_SECOND_USERNAME = "jonathangabriel.carvalho@gmail.com"
AUTH_LEAKED_USERNAME = "CF_EXPOSED_USERNAME@example.com"

[[env.production.routes]]
pattern = "democredentialstuffing.jonathangoc.com"
custom_domain = true
