name = "cloudflare-demo-hub-aichatbot"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[env.production]
name = "cloudflare-demo-hub-aichatbot"

[[env.production.routes]]
pattern = "demoaichatbot.jonathangoc.com"
custom_domain = true
